# Generated by Django 3.0.4 on 2020-03-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20200327_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boomer',
            name='requests',
        ),
        migrations.AddField(
            model_name='requests',
            name='boomer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='corona.Boomer'),
            preserve_default=False,
        ),
    ]
