# Generated by Django 3.0.4 on 2020-03-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20200328_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='zoomer_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requests',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
