# Generated by Django 3.0.4 on 2020-03-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_auto_20200328_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='zoomer_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
