# Generated by Django 3.0.4 on 2020-03-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0005_auto_20200328_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='zoomer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
