# Generated by Django 3.0.4 on 2020-03-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_auto_20200328_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='boomer',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='boomer',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='boomer',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='zoomer',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zoomer',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zoomer',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
